apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: weather-client
  template:
    metadata:
      labels:
        app: weather-client
    spec:
      containers:
        - name: weather-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
