apiVersion: v1
kind: Service
metadata:
  name: weather-client
spec:
  type: NodePort
  selector:
    app: weather-client
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
